In [1]:
import pandas as pd

## Read a .csv from a URL with Pandas

#### Target Website: https://www.football-data.co.uk/englandm.php

In [3]:
# read 1 .csv file from the website
df_premier21 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2122/E0.csv')

In [4]:
# Showing Data Frame
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,E0,26/02/2022,15:00,Man United,Watford,0,0,D,0,0,...,2.15,-1.25,1.87,2.03,1.88,2.05,1.91,2.19,1.86,2.03
253,E0,26/02/2022,15:30,Brighton,Aston Villa,0,2,A,0,1,...,1.70,-0.25,1.91,1.99,1.93,2.00,1.96,2.02,1.90,1.97
254,E0,26/02/2022,17:30,Everton,Man City,0,1,A,0,0,...,2.50,1.75,1.92,1.98,2.01,1.89,2.05,1.99,1.95,1.92
255,E0,27/02/2022,14:00,West Ham,Wolves,1,0,H,0,0,...,1.63,-0.50,1.94,1.96,1.94,1.98,1.97,2.00,1.94,1.94
256,E0,01/03/2022,19:45,Burnley,Leicester,0,2,A,0,0,...,1.81,0.25,1.75,2.17,1.74,2.23,1.85,2.26,1.73,2.18

In [6]:
# rename columns
df_premier21.rename(columns={'FTHG':'home_goals',
                            'FTAG':'away_goals'}, inplace=True)

In [7]:
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,E0,26/02/2022,15:00,Man United,Watford,0,0,D,0,0,...,2.15,-1.25,1.87,2.03,1.88,2.05,1.91,2.19,1.86,2.03
253,E0,26/02/2022,15:30,Brighton,Aston Villa,0,2,A,0,1,...,1.70,-0.25,1.91,1.99,1.93,2.00,1.96,2.02,1.90,1.97
254,E0,26/02/2022,17:30,Everton,Man City,0,1,A,0,0,...,2.50,1.75,1.92,1.98,2.01,1.89,2.05,1.99,1.95,1.92
255,E0,27/02/2022,14:00,West Ham,Wolves,1,0,H,0,0,...,1.63,-0.50,1.94,1.96,1.94,1.98,1.97,2.00,1.94,1.94
256,E0,01/03/2022,19:45,Burnley,Leicester,0,2,A,0,0,...,1.81,0.25,1.75,2.17,1.74,2.23,1.85,2.26,1.73,2.18